/*
Basic Auth is as authorization where we pass the username and passord along with the request as auth 
Digest Authorization it uses the same method as the basic auth but the data is encrypted in MD5 hashed form not in plain text
Bearer Token Authorization will have a token that has been generated by the client previously tha thas certain tim
*/

describe('Authorization types in API',()=>{

    // Bearer Token
    let bearerToken='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'
    
    // Basic Auth 
    it('Authorization using Basic auth',()=>{

        // Get request in basic auth
        cy.request({
            method:'GET',
            url:'https://postman-echo.com/basic-auth',
            auth:{
                user:"postman",
                pass:"password"
            }
        }).then((response)=>{
            expect(response.status).to.eq(200)
            expect(response.body.authenticated).to.eq(true)
        })
    })

    // Digest Auth 
    it.skip('Authorization using Digest auth',()=>{

        // Get request in Digest auth
        cy.request({
            method:'GET',
            url:'https://postman-echo.com/digest-auth',
            auth:{
                user:"postman",
                pass:"password",
                type:'digest'
            }
        }).then((response)=>{
            expect(response.status).to.eq(200)
            expect(response.body.authenticated).to.eq(true)
        })
    })

    // Bearer Token
    it('Bearer Token Atuh',()=>{

        // Get request with Bearer Token
        cy.request({
            method:'GET',
            url:'https://api.github.com/user/repos',
            headers:{
                Authorization:'Bearer '+bearerToken
            }
        }).then((response)=>{
            expect(response.status).to.eq(200)
        })
    })

    // API key
    it('API key Authorization',()=>{
        //const queryParam={q:chennai}
        // Get request with API key
        cy.request({
            method:'GET',
            url:'https://api.openweathermap.org/data/2.5/weather?q=chennai',
            qs:{
                appid:'c1ba3f78929988d5bb8d57a758e1b954'
            }
        }).then((response)=>{
            expect(response.status).to.eq(200)
        })
    })
})